run:
  tests: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - megacheck
    - misspell
    - nakedret
    - nestif
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - wastedassign
    - whitespace
  disable:
    - gochecknoglobals # disabled since we use a global variable to define the application version
    - gochecknoinits # disabled since we an init function to configure sentry
    - golint # deprecated, use revive instead
    - gosimple # deprecated, use staticcheck instead
    - interfacer # deprecated, no replacement suggested
    - unused # deprecated, use staticcheck instead
    - maligned # deprecated, replaced by govet 'fieldalignment'
    - scopelint # deprecated, replaced by exportloopref
    - wsl
  fast: false

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/alessio-perugini/f1calendarbot
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/alessio-perugini/f1calendarbot)
    section-separators:
      - newLine
