version: "2"
run:
  build-tags:
    - integration
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_gen.go$
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/alessio-perugini/f1calendarbot)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/alessio-perugini/f1calendarbot
  exclusions:
    generated: lax
    paths:
      - .*_gen.go$
      - third_party$
      - builtin$
      - examples$
